### ISSUE TITLE
Fix Kodi 17

### ISSUE THREAD

**Issue by ShayBox** [wackerl91/script.luna#129]
- Luna Version: 0.7.0-rc5 (But all do it)
- nVidia GeForce Experience Version: 3.3.0.95
- Moonlight Embedded Version: Latest
- OSMC Version: 1-1-2017 Updated to Kodi 17

**Expected Behaviour:**
To Work
**Actual Behaviour:**
Not Working

Install, Pair, and Freezes and Crashes on Getting information for Minecraft, which isn't in my GFE gamelist, but its looking for it anyway. Worked in Kodi 16, Kodi 17 broke it, update Luna to work

**Comment by wackerl91** [comment]
Thanks for the report.
I will investigate this and try to fix it as soon as I can find some time.

What really bothers me is this:

> Getting information for Minecraft, which isn't in my GFE gamelist, but its looking for it anyway

I guess that it's installed on your PC, everything else would be pretty weird. Are you absolutely positive that it's shown neither on the "start" screen of GFE nor has been added manually in the past (the list of manually added games should be somewhere in the settings)?

**Comment by ShayBox** [comment]
I do have it installed, but I didn't add it to the GFE list, and its not there right now... so I don't know why Luna is trying to find it

**Comment by wackerl91** [comment]
Well, most probably because it's reported by GFE. The entire list is pulled directly from the host and nothing is really added or removed by Luna, all that happens is just processing the list entries to add covers, etc if they are new. To decrease processing times all old values are cached and stale entries should be removed from the cache ... an invalid cache shouldn't be the case either, as no attempts on getting information are done for cached entries (that would very obviously defeat the purpose).
That being said, GFE is really weird at times and the 3.x versions especially so: on my PC it shows Paragon (right on the overview screen) and it's also listed as supported on Nvidia's website, but it never ever shows up when pulling the list (neither when using moonlight's CLI).
In the end I wouldn't bother too much about it to be honest. The crashes you're seeing are most likely not related to a single game anyway.

**Comment by wackerl91** [comment]
I had a look at this with a fresh OSMC 2017-2 installation, including Kodi 17.
Installing, pairing and listing games does work, but there are some major interface issues (missing backgrounds, game posters aren't loaded properly, some style inconsistencies and the like).
Streaming works as well.

So basically, apart from it being ugly right now, it's not completely broken.

@ShayBox Please make sure that you're not having the same issue as described in #130 (OMDB API doesn't work anymore).

**Comment by ShayBox** [comment]
I got it working again, I had flashed 2017-2-2 OSMC and tried again, and it
worked.

**Comment by wackerl91** [comment]
Well, since your initial issue seems to have solved itself and most of the interface fixes are already part of the latest RC, I'll close this issue.

Feel free to re-open it if it stops working again for some reason.

Again, thanks for the report!
