### ISSUE TITLE
xbox360 wired Controller - Right Config

### ISSUE THREAD

**Issue by BoBBer446** [wackerl91/script.luna#145]
All Versions up to Day: Today
How i can config Xbox360 wired Controller?
There many different ways to config...
have i do step one this:
https://github.com/irtimmer/moonlight-embedded/wiki/Controllers-set-up

and step two:
https://github.com/wackerl91/luna/wiki/Controller-Configuration

or only one of the configs?

**Comment by wackerl91** [comment]
@BoBBer446 
The controller config posted on Luna's Wiki is kind of outdated since it aimed at setting up the controller to work in both Kodi and moonlight. With OSMC / Kodi having a controller config tool on their own now, that's not necessary anymore.

In short, for any installations where you don't need controller hot-plugging just follow the steps listed in moonlight-embedded's Wiki and you should be fine.

**Comment by BoBBer446** [comment]
Thank you for quick response!
Okay, I have to set up controller like descripted on moonlight-embedded right?
Then i config the input in Kodi direct.

But often the button x and y is not right.
On no man's sky is x=y and y=x 
That's at Skyrim special edition too

Hitman runs great.

What I have to do on Luna controller setup mapping? Leaving it or run moonlight map one.map and press the buttons ?

Sorry for many questions

**Comment by wackerl91** [comment]
Either configure the X/Y swap directly when starting the driver [like mchrbn did](https://github.com/wackerl91/luna/issues/83#issuecomment-270383326) (note that you might need to re-run Kodi's controller configuration) **or** shut down Kodi, use moonlight's mapping command, start Kodi again and add the created mapping file to your controller using Luna's controller configuration screen.

I'm usually doing the latter since it always produced the desired outcome for me so far and moonlight takes care of any button translations necessary. Plus I can use the mapping file for all my X360 controllers without needing to remember to append any necessary button swaps.

As a general note, Luna's 'Create mapping' functionality is [broken right now](https://github.com/wackerl91/luna/issues/83), so if you want to create one you should stick to moonlight's CLI. Only general controller configuration (selecting controllers, adding already created mapping files) works.

**Comment by BoBBer446** [comment]
I have to add this:
`xboxdrv --detach-kernel-driver --buttonmap du=dl,dl=du,dd=dr,dr=dd,x=y,y=x --silent`
to
`/etc/rc.local`
?

I do this:

Clean OSM Install
config KODI/OSMC
sudo modprobe -r xpad
sudo nano `/etc/modprobe.d/gamepad.conf` and ADD this: `blacklist xpad`
`sudo apt-get install xboxdrv`

Then i type `sudo xboxdrv`, result:
```
osmc@osmc:~$ sudo xboxdrv
xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmx.de>
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions; see the file COPYING for details.

Controller:        Microsoft Xbox 360 Controller
Vendor/Product:    045e:028e
USB Path:          001:004
Controller Type:   Xbox360

-- [ ERROR ] ------------------------------------------------------
 Error couldn't claim the USB interface: LIBUSB_ERROR_BUSY
Try to run 'rmmod xpad' and then xboxdrv again or start xboxdrv with the option --detach-kernel-driver.
osmc@osmc:~$ rmmod xpad
rmmod: ERROR: Module xpad is not currently loaded
osmc@osmc:~$
```
i try then 
`moonlight map xbox360.map`

i config and i set this mapping to luna settings.

But for now i try to read manpage and find a solution that work for me :)

Thank you for helping me :)

**Comment by BoBBer446** [comment]
Although the error comes, the controller works.

But also if I `moonligt map four.map` entries and instead of x then press y and instead of y then x it is exactly the same in the game. X=Y and Y=x

If i run
sudo xboxdrv --detach-kernel-driver --buttonmap du=dl,dl=du,dd=dr,dr=dd,x=y,y=x --silent

i geht the same issue:
```
xboxdrv 0.8.5 - http://pingus.seul.org/~grumbel/xboxdrv/
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmx.de>
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions; see the file COPYING for details.

Controller:        Microsoft Xbox 360 Controller
Vendor/Product:    045e:028e
USB Path:          001:004
Controller Type:   Xbox360

-- [ ERROR ] ------------------------------------------------------
 Error couldn't claim the USB interface: LIBUSB_ERROR_BUSY
Try to run 'rmmod xpad' and then xboxdrv again or start xboxdrv with the option --detach-kernel-driver.
osmc@osmc:~$ rmmod xpad
rmmod: ERROR: Module xpad is not currently loaded
```

Do you know why this is so?

**Comment by wackerl91** [comment]
This discussion continues in #148.
