### ISSUE TITLE
Android Port possible?

### ISSUE THREAD

**Issue by ErAzOr2k** [wackerl91/script.luna#149]
Hi,

is a android port for this nice plugin possible? if yes, is it planned?

**Comment by wackerl91** [comment]
That's what [Moonlight's Android Port](https://play.google.com/store/apps/details?id=com.limelight) is good for ;)

So as far as Luna is concerned: not likely. Given that there's already an app available from the moonlight devs and I'd need to use basically their entire code base (minus the UI) that's too much trouble and doesn't provide any benefit over their original app except that it would look different ... even more so because GUI stuff isn't really my strongest suit, which is very apparent when you have a look at all the GUI glitches in Luna :P

I'm using moonlight on my tablet with a PS3 controller from time to time and it's great fun, really :) So just go ahead, download their app and thank them for their good work!
