### ISSUE TITLE
Kodi still appears un the screen when I open games (kodi not osmc)

### ISSUE THREAD

**Issue by Rubikaz** [wackerl91/script.luna#166]
- Luna Version: Luna 0.7.0-rc7 for kodi (not osmc) https://github.com/meveric/luna
- nVidia GeForce Experience Version: 3.12.0.84
- Moonlight Embedded Version: last one
- OSMC Version: not osmc, just kodi 17.4 (raspbian + kodi 17.4)

When I open steam I can hear the sound of the program but the screen still shows Kodi. If I close Kodi then the screen shows me the streaming from the PC.

It seems that the problem is that the addon does not close kodi. If I execute moonlight via a ssh connection I get the same problem (I can not see it till I close kodi).

About my system, I did the following modifications to get the shutdown functions in kodi (I do not know if it is important) https://www.raspberrypi.org/forums/viewtopic.php?t=108209

Thank you

**Comment by wackerl91** [comment]
That's probably because the service `mediacenter` is not available on your system and thus can't be shut down with the [command used in the launch script](https://github.com/wackerl91/luna/blob/develop/resources/lib/launchscripts/osmc/launch-helper-osmc.sh#L28).
You'll need to change the launch scripts the match your setup. You can find some inspirations in some of the forks, e.g. [this one](https://github.com/leonharv/luna).

Moonlight itself never closes Kodi.
